### ISSUE TITLE
Executor and Scheduler methods

### ISSUE THREAD

**Issue by charconstpointer** [procyon-projects/chrono#1]
Executor and Scheduler both share similar methods, for example :
> Executor
```
Schedule(task Task, delay time.Duration) (ScheduledTask, error)	
ScheduleWithFixedDelay(task Task, initialDelay time.Duration, delay time.Duration) (ScheduledTask, error)
ScheduleAtFixedRate(task Task, initialDelay time.Duration, period time.Duration) (ScheduledTask, error)
```

and 
> Scheduler
```
Schedule(task Task, options ...Option) (ScheduledTask, error)	
ScheduleWithFixedDelay(task Task, delay time.Duration, options ...Option) (ScheduledTask, error)	
ScheduleAtFixedRate(task Task, period time.Duration, options ...Option) (ScheduledTask, error)
```

Don't you think this could be confusing considering that both interfaces are exported in the same package?

**Comment by burakkoken** [comment]
Actually, I don't think this situation could be confusing. Scheduler makes use of Executor and its methods. I mean Scheduler provides an abstract layer. For example, if you use Scheduler to schedule your tasks, you won't need to calculate the initial delay. You can also do the same thing with Executor.
 
But the main reason why I exported both Executor and Scheduler interface is to make the library extensible. This means everyone can implement their Executor and Scheduler.

I hope I answered your question clearly.

**Comment by burakkoken** [comment]
Due to inactivity, this issue was closed.
