### ISSUE TITLE
Shutdown one-shot scheduler

### ISSUE THREAD

**Issue by yufeng1707** [procyon-projects/chrono#11]
I am currently using the one-shot scheduler to end an event. I want to shutdown that scheduler after the event is ended. However, I don't know where to put the shutdown code.
The event ending scheduler look like this:
```go
	repo.endScheduler = chrono.NewDefaultTaskScheduler()
	endTime := time.Unix(event.EndTime, 0)
	if _, err := repo.endScheduler.Schedule(func(ctx context.Context) {
		err := repo.end(event.ID)
		if err != nil {
			log.Fatalf("Failed to end event: %v\n", err)
		} else {
			log.Println("Event ended.")
		}
	}, chrono.WithTime(endTime)); err != nil {
		log.Fatalf("Failed to schedule event end time: %v\n", err)
		return nil, err
	}
```
My question is: Will the fact that I am not shutting down the scheduler affect the performance of my application? If it will, then how should I do it?
Thank you in advance for your attention.

**Comment by burakkoken** [comment]
Not shutting down the scheduler does not affect the performance of your application. When there is no scheduled task, the scheduled will be in sleep mode until a new scheduled task arrives :)
