### ISSUE TITLE
Tests not working correct

### ISSUE THREAD

**Issue by Dexus** [procyon-projects/chrono#8]
The tests, showing some problems:

```
Running tool: /usr/local/go/bin/go test -timeout 1m30s -run ^TestCronExpression_NextTime$ **/chrono -v

=== RUN   TestCronExpression_NextTime
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:18 +0100 CET expected: 2021-03-16 15:04:17 +0000 UTC
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:21 +0100 CET expected: 2021-03-16 15:04:20 +0000 UTC
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:24 +0100 CET expected: 2021-03-16 15:04:23 +0000 UTC
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:27 +0100 CET expected: 2021-03-16 15:04:26 +0000 UTC
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:30 +0100 CET expected: 2021-03-16 15:04:29 +0000 UTC
    **/chrono/cron_test.go:634: got: 2021-03-16 15:10:33 +0100 CET expected: 2021-03-16 15:04:32 +0000 UTC
--- FAIL: TestCronExpression_NextTime (0.00s)
FAIL
FAIL	github.com/Dexus-Forks/chrono	0.005s

```

**Comment by burakkoken** [comment]
Thank you for reporting this, I'm gonna investigate what causes this. 

Which go version do you use?

**Comment by Dexus** [comment]
Always the latest, 1.17.*

Von meinem iPhone gesendet

**Comment by burakkoken** [comment]
I could not reproduce this behavior. However, I'm gonna add go 1.17.5 version into .travis.yaml to reproduce in the pipeline.
 
I'm using the go1.17.5
```
burakkoken@Burak-MacBook-Pro chrono % go version
go version go1.17.5 darwin/arm64
```

The execution result is **PASS**
```
burakkoken@Burak-MacBook-Pro chrono % go test -timeout 1m30s -run ^TestCronExpression_NextTime$
PASS
ok      github.com/procyon-projects/chrono      0.362s
```

**Comment by burakkoken** [comment]
As you can see, the test executions and build in the travis pipeline are completed successfully.
I have tried it on both my local and travis environment, everything works as expected.
This might be a issue with your local environment. @Dexus 

<img width="1114" alt="Ekran Resmi 2021-12-12 12 01 12" src="https://user-images.githubusercontent.com/5354910/145727617-a2e2ce0c-4214-4d9c-be29-73649ebb60c3.png">

**Comment by burakkoken** [comment]
Hi @Dexus, the tests are executed properly in your local environment?

**Comment by burakkoken** [comment]
**Note:** This issue will be closed within 7 days due to inactivity. please give needed information.
